apiVersion: v1
kind: Pod
metadata:
  name: manjapod
  labels:
    app: proxy
  
  spec:
  containers:
  - name: manjacontainer
    image: anjandevop/stand-alone
    ports:
      - containerPort: 8080
   
         
---
apiVersion: v1
kind: Service
metadata:
  name: anjan-service
spec:
  selector:
    app: proxy
  ports:
   - port: 80
     targetPort: 8080
  type: NodePort
  
