apiVersion: v1
kind: Pod
metadata:
  name: manjapod
  labels:
    app: proxy
  tolerations:
     - key: "node-role.kubernetes.io/master"
       operator: "Exists"
       effect: "NoSchedule"
       
spec:
  containers:
  - name: manjacontainer
    image: anjandevop/maven-standalone-application
    ports:
      - containerPort: 8080
   
         

---
apiVersion: v1
kind: Service
metadata:
  name: manja-service
spec:
  selector:
    app: proxy
  ports:
   - port: 80
     targetPort: 8080
  type: NodePort
  
