apiVersion: v1
kind: Pod
metadata:
  name: anjan
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: Anjan
    image: anjandevop/maven-standalone-application
    ports:
      - containerPort: 8080
        

---
apiVersion: v1
kind: Service
metadata:
  name: anjan-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
   - port: 80
     targetPort: 8080
  type: NodePort
  
